### ISSUE TITLE
LibGuides home - 2 columns

### ISSUE THREAD

**Issue by stefaniebuck001** [osulp/LibGuides#14]
can we make the list of guides 2 columns? Is that easy to do? See http://guides.library.stonybrook.edu/ for an example

**Comment by mickeroo** [comment]
Yes, **I have made this change live**.    Here's how to do it: 

This is a setting in Page Layout -> Homepage -> Customize Homepage Templates -> Homepage with links  then set as below: 
<img width="479" alt="screen shot 2015-09-03 at 4 51 25 pm" src="https://cloud.githubusercontent.com/assets/2022754/9673709/16118f68-525c-11e5-8019-2ba82889bd6d.png">
